### ISSUE TITLE
Weird Bug in Word Problem

### ISSUE THREAD

**Issue by sherrysk8r** [sherryxue/Kohikohi#24]
Can't figure out how to get singular and plural check working.
The # is still there sometimes. It will say n#.

**Comment by mingyanw** [comment]
I can take a look at this after I finish implementing timer!

**Comment by mingyanw** [comment]
Fixed the "n#" bug - the indices originally got messed up when one of the n's is 10 since that takes up 2 characters (versus 1). Applied the quick & easy fix of decreasing the upper-range to 9. If time allots, will tweak the fillInQuestionTemplate method to accommodate variable digit (1, 2, 3) randNums.

**Comment by sherryxue** [comment]
Thank you!
